export const todoTypes = {
  CREATE_TODO: 'CREATE_TODO',
  CREATE_TODO_NEW_MONTH: 'CREATE_TODO_NEW_MONTH',
  GET_TODO_LIST: 'GET_TODO_LIST',
  GET_TODO: 'GET_TODO',
  EDIT_TODO: 'EDIT_TODO',
  DELETE_TODO: 'DELETE_TODO',
};
