export const appTypes = {
  INITIAL_DATA_FETCH: 'INITIAL_DATA_FETCH',
  FETCH_DATA_BY_DATE: 'FETCH_DATA_BY_DATE',
  SELECTED_DATE_CHANGE: 'SELECTED_DATE_CHANGE',
  USER_LOGOUT: 'USER_LOGOUT',
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  HIDE_SNACKBAR: 'HIDE_SNACKBAR',
  CHANGE_USER_SETTING: 'CHANGE_USER_SETTING',
};
